In [27]:
import pandas as pd

d = {
    "Name": ["Dinesh", "Anurodh", "Bivhas", "Anwarul", "Paras", "Ram"],
    "Age": [20, 21, 19, 22, 18, 23],
    "Marks": [85, 90, 78, 92, 99, 97]
}

df = pd.DataFrame(d)

print(df)

      Name  Age  Marks
0   Dinesh   20     85
1  Anurodh   21     90
2   Bivhas   19     78
3  Anwarul   22     92
4    Paras   18     99
5      Ram   23     97

In [28]:
print(df.head(5))

      Name  Age  Marks
0   Dinesh   20     85
1  Anurodh   21     90
2   Bivhas   19     78
3  Anwarul   22     92
4    Paras   18     99

In [29]:
print(df.tail(5))

      Name  Age  Marks
1  Anurodh   21     90
2   Bivhas   19     78
3  Anwarul   22     92
4    Paras   18     99
5      Ram   23     97

In [30]:
df.shape

(6, 3)

In [31]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   Marks   6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

In [33]:
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   20.500000  90.166667
std     1.870829   7.782459
min    18.000000  78.000000
25%    19.250000  86.250000
50%    20.500000  91.000000
75%    21.750000  95.750000
max    23.000000  99.000000

In [34]:
df["Name"]

0     Dinesh
1    Anurodh
2     Bivhas
3    Anwarul
4      Paras
5        Ram
Name: Name, dtype: object

In [35]:
df[["Name", "Marks"]]

      Name  Marks
0   Dinesh     85
1  Anurodh     90
2   Bivhas     78
3  Anwarul     92
4    Paras     99
5      Ram     97

In [36]:
df.iloc[0]

Name     Dinesh
Age          20
Marks        85
Name: 0, dtype: object

In [37]:
df.loc[0]

Name     Dinesh
Age          20
Marks        85
Name: 0, dtype: object

In [38]:
df.loc[0, "Marks"]

np.int64(85)

In [39]:
df[df["Marks"] > 80]

      Name  Age  Marks
0   Dinesh   20     85
1  Anurodh   21     90
3  Anwarul   22     92
4    Paras   18     99
5      Ram   23     97

In [40]:
df[(df["Age"] > 20) & (df["Marks"] > 75)]

      Name  Age  Marks
1  Anurodh   21     90
3  Anwarul   22     92
5      Ram   23     97

In [41]:
df["Grade"] = ["PHD", "+2", "11", "Bachelor", "Masters", "10"]
print(df)

      Name  Age  Marks     Grade
0   Dinesh   20     85       PHD
1  Anurodh   21     90        +2
2   Bivhas   19     78        11
3  Anwarul   22     92  Bachelor
4    Paras   18     99   Masters
5      Ram   23     97        10

In [42]:
df["Marks"] = df["Marks"] + 5
print(df)

      Name  Age  Marks     Grade
0   Dinesh   20     90       PHD
1  Anurodh   21     95        +2
2   Bivhas   19     83        11
3  Anwarul   22     97  Bachelor
4    Paras   18    104   Masters
5      Ram   23    102        10

In [43]:
df.loc[df["Name"]=="Dinesh", "Marks"] = 98
print(df)

      Name  Age  Marks     Grade
0   Dinesh   20     98       PHD
1  Anurodh   21     95        +2
2   Bivhas   19     83        11
3  Anwarul   22     97  Bachelor
4    Paras   18    104   Masters
5      Ram   23    102        10

In [44]:
df.drop("Age", axis=1)

      Name  Marks     Grade
0   Dinesh     98       PHD
1  Anurodh     95        +2
2   Bivhas     83        11
3  Anwarul     97  Bachelor
4    Paras    104   Masters
5      Ram    102        10

In [45]:
df.drop(0, axis=0)

      Name  Age  Marks     Grade
1  Anurodh   21     95        +2
2   Bivhas   19     83        11
3  Anwarul   22     97  Bachelor
4    Paras   18    104   Masters
5      Ram   23    102        10

In [46]:
print(df)

      Name  Age  Marks     Grade
0   Dinesh   20     98       PHD
1  Anurodh   21     95        +2
2   Bivhas   19     83        11
3  Anwarul   22     97  Bachelor
4    Paras   18    104   Masters
5      Ram   23    102        10

In [47]:
df.sort_values("Marks")

      Name  Age  Marks     Grade
2   Bivhas   19     83        11
1  Anurodh   21     95        +2
3  Anwarul   22     97  Bachelor
0   Dinesh   20     98       PHD
5      Ram   23    102        10
4    Paras   18    104   Masters

In [48]:
df.sort_values("Marks", ascending=False)

      Name  Age  Marks     Grade
4    Paras   18    104   Masters
5      Ram   23    102        10
0   Dinesh   20     98       PHD
3  Anwarul   22     97  Bachelor
1  Anurodh   21     95        +2
2   Bivhas   19     83        11

In [49]:
import pandas as pd

d = {
    "Name": ["Dinesh", "Anurodh", "Bivhas", "Anwarul", "Paras", "Ram"],
    "Age": [20, 21, 19, 22, 18, 23],
    "Marks": [85, 90, 78, 92, 99, 97]
}

df1 = pd.DataFrame(d)

print(df1)

      Name  Age  Marks
0   Dinesh   20     85
1  Anurodh   21     90
2   Bivhas   19     78
3  Anwarul   22     92
4    Paras   18     99
5      Ram   23     97

In [50]:
import pandas as pd

d = {
    "Name": ["Lex", "Aly", "Rex", "Alice", "Alex", "Sly"],
    "Age": [20, 19, 18, 20, 22, 23],
    "Marks": [80, 91, 73, 90, 90, 78]
}

df2 = pd.DataFrame(d)

print(df2)

    Name  Age  Marks
0    Lex   20     80
1    Aly   19     91
2    Rex   18     73
3  Alice   20     90
4   Alex   22     90
5    Sly   23     78

In [51]:
pd.concat([df1, df2])

      Name  Age  Marks
0   Dinesh   20     85
1  Anurodh   21     90
2   Bivhas   19     78
3  Anwarul   22     92
4    Paras   18     99
5      Ram   23     97
0      Lex   20     80
1      Aly   19     91
2      Rex   18     73
3    Alice   20     90
4     Alex   22     90
5      Sly   23     78

In [55]:
df = pd.read_csv("attendance.csv")
df

,Student_ID,Roll,Name,Department,Time,Date,Status
0,230305,23070382,Anwarul Ansari,ICT,07:41:01,20/02/2026,Present
1,230315,23070392,Dinesh Gurung,ICT,07:41:05,20/02/2026,Present
2,230332,232934,Shasank Acharya,ICT,07:47:00,20/02/2026,Present
3,230309,....2323,Bibek Ghimire,ICT,07:49:48,20/02/2026,Present
4,230347,...,Manisha Oli,ICT,07:52:02,20/02/2026,Present
5,23070392,320315,Dinesh Gurung,ICT,20:17:06,03/05/2026,Present

In [58]:
df.to_csv("attendance.csv")